baseURL = "http://example.org/"
languageCode = "en-us"
theme = "PaperMod"
title = "dataSteve"
paginate = 5
[languages.en]
languageName = "English"
weight = 1
[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "Categories"
url = "categories/"
weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
author = "Theme PaperMod"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
images = [ "papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "dataSteve"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Welcome"
  Content = """
dataSteve is my personal blog where I try to post about interesting tech things as often as possible
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/stev2k"

  [[params.socialIcons]]
  name = "RsS"
  url = "index.xml"

  [params.editPost]
  URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true
  
[taxonomies]
category = "categories"
tag = "tags"
series = "series"


