baseURL: 'http://datasteve.net/'
languageCode: en-us
theme: PaperMod
title: dataSteve
paginate: 5
languages:
  en:
    languageName: English
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  env: production
  description: 'My personal tech blog'
  author: Steve Haines
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  images:
    - papermod-cover.png
  profileMode:
    enabled: false
    title: dataSteve
    imageUrl: '#'
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
  homeInfoParams:
    Title: Welcome
    Content: >
      My name is Steve, I have been facinated by computers since I was a child and created my first website using PHP and MySQL when I was about 11.  dataSteve is my latest personal blog where I share things that I am learning on my journey.
  socialIcons:
    - name: github
      url: 'https://github.com/stev2k'
    - name: linkedin
      url: 'https://www.linkedin.com/in/stephen-haines-84893536/'
    - name: twitter
      url: 'https://twitter.com/steve_haines1'
    - name: RsS
      url: index.xml
  editPost:
    URL: 'https://github.com/stev2k/dataSteve/tree/master/content/'
    Text: Suggest Changes
    appendFilePath: true
taxonomies:
  category: categories
  tag: tags
  series: series
  
deployment:
  order:
    - .jpg$
    - .gif$
  targets:
    - name: deployment
      URL: 'gs://www.datasteve.net'
  matchers:
    - pattern: ^.+\.(js|css|svg|ttf)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: true
    - pattern: ^.+\.(png|jpg)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: false
    - pattern: ^sitemap\.xml$
      contentType: application/xml
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true
relativeURLs: true

